{
 "title": "HTTP Requests Metrics",
 "tags": [ "http" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(http_server_requests_seconds_bucket, application)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(http_server_requests_seconds_bucket{application=\"$application\", pod=~\"$pod\"}, method)"
   },
   {
    "name": "uri",
    "label": "URI",
    "query": "label_values(http_server_requests_seconds_bucket{application=\"$application\", pod=~\"$pod\"}, uri)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(process_uptime_seconds{application=\"$application\"}, pod)"
   },
   {
    "name": "latency_percentile",
    "label": "Latency Percentile",
    "query": "99, 95, 90, 75, 65, 50, 35, 25, 10"
   }
  ]
 },
 "panels": [
  {
   "title": "Percentage of all requests served with HTTP 2xx or 3xx, last 1d",
   "type": "singlestat",
   "description": "Percentage of all requests served with HTTP 2xx or 3xx, last 1d",
   "gridPos": { "h": 9, "w": 8, "x": 2, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", status=~\"[2,3][0-9][0-9]\"}[1d])) / sum(increase(http_server_requests_seconds_count{application=\"$application\"}[1d])) * 100"
    }
   ]
  },
  {
   "title": "Percentage of all requests served with HTTP 2xx or 3xx, last 30d",
   "type": "singlestat",
   "description": "Percentage of all requests served with HTTP 2xx or 3xx, last 30d",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", status=~\"[2,3][0-9][0-9]\"}[30d])) / sum(increase(http_server_requests_seconds_count{application=\"$application\"}[30d])) * 100"
    }
   ]
  },
  {
   "title": "Overall Requests by status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", pod=~\"$pod\", method=~\"$method\", uri=~\"$uri\"}[5m]))",
     "legendFormat": "Total req/s"
    },
    {
     "expr": "sum by (status)(rate(http_server_requests_seconds_count{application=\"$application\", pod=~\"$pod\", method=~\"$method\", uri=~\"$uri\"}[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Overall Requests by status - Last Month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Requests per Second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", pod=~\"$pod\", method=~\"$method\", uri=~\"$uri\"}[5m]))",
     "legendFormat": "Total req/s"
    },
    {
     "expr": "sum by (status)(rate(http_server_requests_seconds_count{application=\"$application\", pod=~\"$pod\", method=~\"$method\", uri=~\"$uri\"}[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "$latency_percentile Percentile Latencies by Endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (method, uri)(histogram_quantile(.$latency_percentile, sum by (le, method, uri)(rate(http_server_requests_seconds_bucket{application=\"$application\", pod=~\"$pod\", method=~\"$method\", uri=~\"$uri\"}[5m]))))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "$latency_percentile Percentile Latencies by Endpoint - Last Month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (method, uri)(histogram_quantile(.$latency_percentile, sum by (le, method, uri)(rate(http_server_requests_seconds_bucket{application=\"$application\", pod=~\"$pod\", method=~\"$method\", uri=~\"$uri\"}[5m]))))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Rate by Endpoint/Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (uri, status, method)(rate(http_server_requests_seconds_count{application=\"$application\", method=~\"$method\", uri=~\"$uri\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "Requests Rate by Endpoint/Status - Last Month",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum by (uri, status, method)(rate(http_server_requests_seconds_count{application=\"$application\", method=~\"$method\", uri=~\"$uri\", pod=~\"$pod\"}[5m]))",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  }
 ]
}