version: '3.8'

services:
    postgres:
        image: postgres:13.1-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "example"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            POSTGRES_HOST: "postgres"
            POSTGRES_PASSWORD: "postgres"
        ports:
            - 8080:8080
            - 8082:8082
        volumes:
            - .:/opt/dropwizard-example-app
        depends_on:
          - postgres

    prometheus:
        image: prom/prometheus:v2.24.1
        volumes:
            - ./prometheus:/etc/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yaml'
        ports:
            - 9090:9090

    grafana:
        image: grafana/grafana:7.4.1
        volumes:
            - ./grafana:/etc/grafana
        ports:
            - 3000:3000
        depends_on:
            - prometheus
