global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dropwizard-example-app'
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["app:8082"]
    relabel_configs:
      - source_labels: ["job"]
        target_label: "application"
